### ISSUE TITLE
Update existing students records

### ISSUE THREAD

**Issue by CardExchangeInc** [TheAlphaSchoolSystemPTYLTD/data-upload-utility#18]
Hi team,

Could you point us on how to properly update a student record via the Data Upload Utility? 

We're using the provided methods to upload data but existing data fields are overwritten with null. We expected that the new fields would be added to the existing user while the existing fields would be left as is.

We've already tried using PUT and PATCH requests but these are refused.
Any help would be appreciated.

Thank you for the help
Regards
Luis Silvério @ CardExchange Solutions, Inc.

**Comment by scottetass** [comment]
Hi Luis,

You can either pass only the fields that need updating (with the exception of a couple of mandatory fields such as 'id' which is always needed) or if you are going to pass all fields, then they will need to be provided with their existing values otherwise they will get overwritten with empty string or null.

For example, I just tested this call out with success and it only updated the fields that I provided:

```
{
 "students": [
       {
         "id": "0020920",
         "house": "BA",
         "given_name": "Bruce",
         "surname": "Wayne",
         "preferred_name": "batman"
       }
     ]
 }
```

If the API ignored blank fields, then there would be no way of removing a value from a field, which might be a valid action for someone to perform.

Thanks, Scott
